version: "3.7"

services:
  # PostgreSQL database for storing Ory Hydra data
  postgres:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hydra
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sso-network

  # Ory Hydra - OpenID Connect Provider
  hydra:
    image: oryd/hydra:v2.1.2
    depends_on:
      - postgres
      - hydra-migrate
    ports:
      - "4444:4444" # Public API
      - "4445:4445" # Admin API
    command: serve --dev -c /etc/config/hydra/config.yaml all
    volumes:
      - ./config/hydra:/etc/config/hydra
    environment:
      - DSN=postgres://postgres:postgres@postgres:5432/hydra?sslmode=disable
    networks:
      - sso-network
    restart: on-failure

  # Hydra Migration Service
  hydra-migrate:
    image: oryd/hydra:v2.1.2
    depends_on:
      - postgres
    environment:
      - DSN=postgres://postgres:postgres@postgres:5432/hydra?sslmode=disable
    command: migrate sql -e postgres://postgres:postgres@postgres:5432/hydra?sslmode=disable --yes
    networks:
      - sso-network
    restart: on-failure

  # Login & Consent App Backend
  login-consent-app:
    build:
      context: ./services/login-consent-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HYDRA_ADMIN_URL=http://hydra:4445
      - PORT=3000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/sso_service
      - CORS_ALLOWED_ORIGINS=http://localhost:3010
      # Azure AD / Entra ID Configuration
      - AZURE_CLIENT_ID=YOUR_CLIENT_ID
      - AZURE_CLIENT_SECRET=YOUR_CLIENT_SECRET
      - AZURE_TENANT_ID=YOUR_TENANT_ID
      - AZURE_REDIRECT_URI=http://localhost:3000/auth/azure/callback
      - SESSION_SECRET=your-session-secret
    volumes:
      - ./config/entra-id:/app/config/entra-id
    depends_on:
      - hydra
      - postgres
    networks:
      - sso-network

  # Login & Consent App React Frontend
  login-consent-app-react:
    build:
      context: ./services/login-consent-app-react
      dockerfile: Dockerfile
    ports:
      - "3010:80"
    depends_on:
      - login-consent-app
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - REACT_APP_HYDRA_PUBLIC_URL=http://localhost:4444
    networks:
      - sso-network

  # Admin Portal Backend
  admin-portal:
    build:
      context: ./services/admin-portal
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - HYDRA_ADMIN_URL=http://hydra:4445
      - PORT=3001
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/sso_service
      - CORS_ALLOWED_ORIGINS=http://localhost:3011
    depends_on:
      - hydra
      - postgres
    networks:
      - sso-network

  # Admin Portal React Frontend
  admin-portal-react:
    build:
      context: ./services/admin-portal-react
      dockerfile: Dockerfile
    ports:
      - "3011:80"
    depends_on:
      - admin-portal
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - REACT_APP_HYDRA_ADMIN_URL=http://localhost:4445
    networks:
      - sso-network

networks:
  sso-network:
    driver: bridge

volumes:
  postgres-data:
